services:
  fdp-db-docker:
    image: fdp-db
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - app
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - 5432:5432
    mem_limit: 4Gb
  fdp-app:
    image: fdp-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - fdp-db-docker
    networks:
      - app
    environment:
      - LOG_LEVEL=info
      - DATABASE_URL=postgres://fdp:$DB_PWD@fdp-db-docker:5432/fdp_tickets
    ports:
      - 52017:52017
    mem_limit: 300mb

networks:
  app:
